export const SAVE_BOOKS = 'SCIENCE/SAVE_BOOKS'
export const SAVE_SINGLE_BOOK = 'SCIENCE/SAVE_SINGLE_BOOK'
export const GET_SINGLE_BOOK = 'GET_SINGLE_BOOK'
export const UPDATE_BOOK = 'UPDATE_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'

